package mybank.server.beans;



/**
 * Compte generated by hbm2java
 */

public class Compte  implements ObjetId {
	
	String nomClasse=Compte.class.getName();
	
    private String id;
	
    private TypeObjet typemeteo=TypeObjet.getTypeObjet("TypeMeteo" );
	
    private String iban;
	
    private String description;

    public String getNomClasse() {
		return nomClasse;
	}

	public void setNomClasse(String nomClasse) {
		this.nomClasse = nomClasse;
	}

	public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public TypeObjet getTypemeteo() {
        return typemeteo;
    }

    public void setTypemeteo(TypeObjet typemeteo) {
        this.typemeteo = typemeteo;
    }

    public String getIban() {
        return iban;
    }

    public void setIban(String iban) {
        this.iban = iban;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

	

	public Compte() {
	}



}
