package mybank.server.beans;

// Generated 1 nov. 2016 16:30:23 by Hibernate Tools 4.3.1
import java.util.Date;



/**
 * Messagerie generated by hbm2java
 */

public class Message implements ObjetId {
	
	String nomClasse=Message.class.getName();


	
    String id;
    
    private User contactEmetteur;
    
    private User contactDestinataire;
    
    private String message = "";
    
    private String objet = "";
    
    private boolean lu = false;
    
    private Date timestamp;
    
    public Message() {
    }

    public String getId() {
        return id;
    }

  

    public User getContactEmetteur() {
        return contactEmetteur;
    }

    public void setContactEmetteur(User contactEmetteur) {
        this.contactEmetteur = contactEmetteur;
    }

    public User getContactDestinataire() {
        return contactDestinataire;
    }

    public void setContactDestinataire(User contactDestinataire) {
        this.contactDestinataire = contactDestinataire;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getObjet() {
        return objet;
    }

    public void setObjet(String objet) {
        this.objet = objet;
    }

    public boolean isLu() {
        return lu;
    }

    public void setLu(boolean lu) {
        this.lu = lu;
    }

	public Date getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}
    public String getNomClasse() {
		return nomClasse;
	}

	public void setNomClasse(String nomClasse) {
		this.nomClasse = nomClasse;
	}

	public void setId(String id) {
		this.id = id;
	}
}
