package mybank.server.beans;

/**
 * Optioncontact generated by hbm2java
 */
public class Optioncontact implements java.io.Serializable {

    private String questionsecrete;
    private String reponsesecrete;
    private String telephoneFixe;
    private String telephonePortable;
    private String adresse;
    private String mailrecuperationpassword;

    public Optioncontact() {
    }

    public Optioncontact(User contact, String questionsecrete,
            String reponsesecrete, String telephoneFixe,
            String telephonePortable, String adresse,
            String mailrecuperationpassword) {

        this.questionsecrete = questionsecrete;
        this.reponsesecrete = reponsesecrete;
        this.telephoneFixe = telephoneFixe;
        this.telephonePortable = telephonePortable;
        this.adresse = adresse;
        this.mailrecuperationpassword = mailrecuperationpassword;
    }

    public String getQuestionsecrete() {
        return questionsecrete;
    }

    public void setQuestionsecrete(String questionsecrete) {
        this.questionsecrete = questionsecrete;
    }

    public String getReponsesecrete() {
        return reponsesecrete;
    }

    public void setReponsesecrete(String reponsesecrete) {
        this.reponsesecrete = reponsesecrete;
    }

    public String getTelephoneFixe() {
        return telephoneFixe;
    }

    public void setTelephoneFixe(String telephoneFixe) {
        this.telephoneFixe = telephoneFixe;
    }

    public String getTelephonePortable() {
        return telephonePortable;
    }

    public void setTelephonePortable(String telephonePortable) {
        this.telephonePortable = telephonePortable;
    }

    public String getAdresse() {
        return adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public String getMailrecuperationpassword() {
        return mailrecuperationpassword;
    }

    public void setMailrecuperationpassword(String mailrecuperationpassword) {
        this.mailrecuperationpassword = mailrecuperationpassword;
    }

}
